### ISSUE TITLE
add to cimgui organization?

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimplot#1]
@extrawurst

Just created this repo for implot. Perhaps should be added to cimgui organization?
How should be done given that it is already created?

**Comment by extrawurst** [comment]
Hey @sonoro1234 sure I love it ❤️!
you are an admin in both repos so you should be able to find the `Transfer ownership` section in the projects settings to move it

**Comment by sonoro1234** [comment]
Ok, thanks, I will take a look at Transfer ownership.
