### ISSUE TITLE
set custom path of  implot and cimplot as generator's argument

### ISSUE THREAD

**Issue by gucio321** [cimgui/cimplot#17]
Hi there!
I'm having a problemm in https://github.com/AllenDang/cimgui-go/issues/43
We'd like to use cimplot as a git submodule of cimgui-go, but we met the problemm with paths mentioned above.

In my opinion something like
```sh
sh generator.sh --implot="../thirdparty/implot" --cimgui="../thirdparty/cimgui/cimgui.h"
```
would be more comfortable for people, who use this repository as a git submodule and cannot edit cimplot_template.* file

**Comment by sonoro1234** [comment]
I am sorry but I dont understand the problem.
If you mean running https://github.com/cimgui/cimplot/blob/master/generator/generator.sh to generate cimplot from implot everything looks ok in https://github.com/AllenDang/cimgui-go, it has the same folder structure as https://github.com/sonoro1234/LuaJIT-ImGui

Why should you want to edit cimplot_template.*?

**Comment by sonoro1234** [comment]
As for the problem mentioned in https://github.com/AllenDang/cimgui-go/issues/43#issue-1474142969 I am not sure if it is a building problem. 
```
cd examples
go run .
```
If it is a building problem it should be handled as in https://github.com/sonoro1234/LuaJIT-ImGui/blob/docking_inter/CMakeLists.txt#L7 where the compiler included directories are seting the `-I` flag

**Comment by gucio321** [comment]
Oh, I'm sorry, it seems my report lacks some important information
> If you mean running https://github.com/cimgui/cimplot/blob/master/generator/generator.sh to generate cimplot from implot everything looks ok in https://github.com/AllenDang/cimgui-go, it has the same folder structure as https://github.com/sonoro1234/LuaJIT-ImGui

yah, that part works like a charm!

> Why should you want to edit cimplot_template.*?

I'd like to change include path here
https://github.com/cimgui/cimplot/blob/31a7246b52f7e4e14db6f857aeb72e0ef7b3f3ad/cimplot.h#L7
from `cimgui.h` to `../cimgui/cimgui.h`, since it is a valid path for our repo.
The problemm is, that CGO compiler keeps the folder structure, so the path there needs to point the exact location of cimgui.h

**Comment by sonoro1234** [comment]
googling: `CGO compiler include paths` 

Perhaps this can help? https://stackoverflow.com/questions/38381357/how-to-point-to-c-header-files-in-go

`-I` flag must be setted somehow as can be done in any C compiler

**Comment by gucio321** [comment]
> googling: CGO compiler include paths
>
>Perhaps this can help? https://stackoverflow.com/questions/38381357/how-to-point-to-c-header-files-in-go
>
>-I flag must be setted somehow as can be done in any C compiler

yah, but the problemm is on the C side: cimplot's header cannot find cimgui.h, because it looks for `./cimplot/cimgui.h`, but the file doesn't exist

When I manually edit cimplot.h, the problemm dissappears

It is also possible that I missunderstand C, since I'm not an expert :smile:

**Comment by sonoro1234** [comment]
> yah, but the problemm is on the C side: cimplot's header cannot find cimgui.h, because it looks for `./cimplot/cimgui.h`, but the file doesn't exist

Not at all. It does not look for `./cimplot/cimgui.h` but for `cimgui.h` anywhere in the `include paths`. (They are set by the `-I` flags as I told you  before)

**Comment by gucio321** [comment]
Oh ok, thx
Will test tomorrow

**Comment by eliasdaler** [comment]
Looks like [XY Problem](https://xyproblem.info/). The problem here is that you didn't change CGo include paths, with them it `#include "cimgui.h"` doesn't need to be changed in any way.

**Comment by gucio321** [comment]
Probably, you're right, there is everything OK with cimplot  :smile:
Closing for now.
