### ISSUE TITLE
Failed to compile the header cimplot.h because it’s not self-contained

### ISSUE THREAD

**Issue by Gnimuc** [cimgui/cimplot#5]
Types like ImVec2 are used in the header but there is no definition or reference to the definition in other headers like cimgui.h.

**Comment by sonoro1234** [comment]
cimplot.cpp includes implot.h which includes imgui.h
What are you trying to compile specifically?

**Comment by Gnimuc** [comment]
I'm actually trying to generate bindings for other language using Clang. The header file in C serves as an interface which should tell the exact size of the type defined in it. 

Another case is that if one would like to use the precompiled binary in a project, how could it be compiled if there are unknown types in the header?

**Comment by sonoro1234** [comment]
Just moved #include implot.h to cimplot.h
Is that enough?

**Comment by sonoro1234** [comment]
Surely you will need to add `cimgui/imgui` to included directories to succeed (-I flag in gcc)

**Comment by Gnimuc** [comment]
> Just moved #include implot.h to cimplot.h
> Is that enough?

Maybe it should be `#include "cimgui.h"`?  `implot.h` is a C++ header, if we would like to expose a self-contained C API, any C++ type should be wrapped to a C counterpart. For example, in cimgui.h, [`imgui.h`'s ImVec2](https://github.com/ocornut/imgui/blob/45c45d250618ccdd573f5eef01390c6689077c46/imgui.h#L230) is wrapped to [`cimgui.h`'s ImVec2](https://github.com/cimgui/cimgui/blob/ea9720b4124dde851e2bcd285d2de6da8f6f24f9/cimgui.h#L294). I think we should do the same thing in cimplot.h.

**Comment by Gnimuc** [comment]
Maybe something like this:
```c
#ifdef INCLUDE_CIMGUI_H
    #include "cimgui.h"
#else

#endif // INCLUDE_CIMGUI_H
```

**Comment by sonoro1234** [comment]
Done.
Is that ok?

**Comment by Gnimuc** [comment]
I've left a comment in that commit. Would you mind also update the binding for [implot-v0.9](https://github.com/epezent/implot/releases/tag/v0.9)?

**Comment by sonoro1234** [comment]
> Would you mind also update the binding for [implot-v0.9](https://github.com/epezent/implot/releases/tag/v0.9)?

Just done.

I guess I should do include cimgui.h the same way done here in all other cimgui modules.

**Comment by Gnimuc** [comment]
Thanks a lot! btw, don't forget to push the tags 😉
