### ISSUE TITLE
error: unknown type name 'time_t'

### ISSUE THREAD

**Issue by Gnimuc** [cimgui/cimplot#9]
Looks like  <kbd>time.h</kbd> is missed in the <kbd>cimplot.h</kbd>.

```
#include <time.h>
```

**Comment by Gnimuc** [comment]
Also, the typedef-ed `tm` is missing for `struct tm` in several places:

```
include/cimplot.h:526:5: error: must use 'struct' tag to refer to type 'tm'
include/cimplot.h:1199:12: error: must use 'struct' tag to refer to type 'tm'
include/cimplot.h:1201:12: error: must use 'struct' tag to refer to type 'tm'
include/cimplot.h:1201:53: error: must use 'struct' tag to refer to type 'tm'

```

**Comment by Gnimuc** [comment]
I'm not sure whether this is intended, but this C function proto uses C++-only `&`.

```
CIMGUI_API void ImPlotTickCollection_Append_double(ImPlotTickCollection* self,double value,bool major,bool show_label,void(*labeler)(ImPlotTick& tick,ImGuiTextBuffer& buf));
```

**Comment by sonoro1234** [comment]
> Looks like time.h is missed in the cimplot.h.

cimplot.h is a "dual header": when `CIMGUI_DEFINE_ENUMS_AND_STRUCTS` is defined it is a C header elsewhere is a C++ header.
As a C++ header it doesnt need time.h that is already included in implot.h but as a C header it needs it.
Solutions are: include time.h yourself when using it as a C header or otherwise let me modify cimplot.h to include time.h when used as C header.

**Comment by sonoro1234** [comment]
> I'm not sure whether this is intended, but this C function proto uses C++-only `&`.

Yes, that should be corrected!!

**Comment by Gnimuc** [comment]
> Solutions are: include time.h yourself when using it as a C header or otherwise let me modify cimplot.h to include time.h when used as C header.

Why not using `__cplusplus` guards instead of depending on the `CIMGUI_DEFINE_ENUMS_AND_STRUCTS`?

**Comment by sonoro1234** [comment]
> Why not using `__cplusplus` guards instead of depending on the `CIMGUI_DEFINE_ENUMS_AND_STRUCTS`?

CIMGUI_DEFINE_ENUMS_AND_STRUCTS is defined by the user and __cplusplus by the compiler. I feel having more control with the first option.

**Comment by Gnimuc** [comment]
But I'd say this option causes issues. First, let me provide some background.
 
We Julia users have a build-system [BinaryBuilder](https://github.com/JuliaPackaging/BinaryBuilder.jl) and a service [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) for building and shipping C/C++ binaries. 

Those binaries along with the headers are shipped in the form of a "JLL package"  which is **read-only**, so it's not easy to add patches in this stage.

[Clang.jl](https://github.com/JuliaInterop/Clang.jl), based on libclang, provides a binding generator for auto-generating Julia bindings from the headers shipped by those `JLL` packages. 

The problem is that this generator is currently working in a strict-C-mode and libclang just refuses to correctly parse a header that cannot be compiled by a C compiler. 

The `__cplusplus` way is ubiquitously used in the C API headers of many projects. I think we should do the same thing here.

**Comment by sonoro1234** [comment]
> But I'd say this option causes issues.

Which are the issues? Cant you define CIMGUI_DEFINE_ENUMS_AND_STRUCTS with libclang?

**Comment by Gnimuc** [comment]
Those problems reported in this issue are complained by libclang with `-DCIMGUI_DEFINE_ENUMS_AND_STRUCTS` as compiler arguments.

**Comment by sonoro1234** [comment]
> Those problems reported in this issue are complained by libclang with `-DCIMGUI_DEFINE_ENUMS_AND_STRUCTS` as compiler arguments.

Yes, but thats is because we still have not done `include"time.h"` correction

**Comment by Gnimuc** [comment]
Also, we should use `struct tm` instead of `tm`, but maybe `time_t` is a more correct fix?

**Comment by sonoro1234** [comment]
Could you try branch time_include just pushed?
I thing that `struct tm` is handled in time.h also

**Comment by Gnimuc** [comment]
"time.h" works perfectly!

> I thing that struct tm is handled in time.h also

unfortunately, https://stackoverflow.com/questions/29588303/why-is-c-struct-tm-not-as-typedef 😢 

besides, there is only a `C++-only &` issue.

**Comment by sonoro1234** [comment]
the missing struct for tm comes from implot_internal.h. I dont understand why there is no complaint while compiling implot
https://github.com/epezent/implot/blob/95a530f05c267513d044b5ae41bce14883f8a407/implot_internal.h#L1141

**Comment by Gnimuc** [comment]
C++ has that typedef. But here I'm just compiling `cimplot.h` without the cpp source code, so it's pure C.

**Comment by Gnimuc** [comment]
This remains me again that C and C++ are two different languages. 🤣

**Comment by sonoro1234** [comment]
I have added the typedef in branch time_include.

For 

```C
CIMGUI_API void ImPlotTickCollection_Append_double(ImPlotTickCollection* self,double value,bool major,bool show_label,void(*labeler)(ImPlotTick& tick,ImGuiTextBuffer& buf));
```

I am not sure if it should be

```C
CIMGUI_API void ImPlotTickCollection_Append_double(ImPlotTickCollection* self,double value,bool major,bool show_label,void(*labeler)(ImPlotTick tick,ImGuiTextBuffer buf));
```

or

```C
CIMGUI_API void ImPlotTickCollection_Append_double(ImPlotTickCollection* self,double value,bool major,bool show_label,void(*labeler)(ImPlotTick* tick,ImGuiTextBuffer* buf));
```

Could you modify it manually and report?

**Comment by Gnimuc** [comment]
> I have added the typedef in branch time_include.

That works!

> Could you modify it manually and report?

Both ways can be compiled. I guess the correctness can only be tested with a function call.

Maybe we can find some clue from the implot source. But where is this `append` function? I didn't find the one using the `labeler` as a fourth argument:
https://github.com/epezent/implot/blob/27bc59eb434624f9660c9d874b7e6e5cbdeef865/implot_internal.h#L528-L574

**Comment by sonoro1234** [comment]
>  I didn't find the one using the `labeler` as a fourth argument:

It is in https://github.com/epezent/implot/blob/95a530f05c267513d044b5ae41bce14883f8a407/implot_internal.h#L550
It seems that it has been dropped in latest implot!!


> Both ways can be compiled. I guess the correctness can only be tested with a function call.

Yes, could you test it?

**Comment by Gnimuc** [comment]
I need to find an example for testing that function. As it's dropped in the latest implot, I guess we can just ignore it in this version.

**Comment by Gnimuc** [comment]
The current time_include branch is enough for my use cases.

**Comment by sonoro1234** [comment]
I have pushed to master. 
The issue is finished?

**Comment by Gnimuc** [comment]
Thanks for all your help!
